const a = new Date();
let year = a.getFullYear();
let month = a.getMonth()+1;
let day = a.getDate();
let hour = a.getHours();
let minute = a.getMinutes();
let passedTime = a.getTime();
console.log(year);
console.log(month);
console.log(day);
console.log(hour);
console.log(minute);
console.log(passedTime);